<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('99', '/uploads/allimg/161130/1-1611301452280-L.png');
$maNum = 1;
$myaddons[$maNum] = array('106', '/uploads/allimg/161130/1-1611301K91MQ.png');
$maNum = 2;
$myaddons[$maNum] = array('107', '/uploads/allimg/161130/1-1611301K94H22.png');
$maNum = 3;
$myaddons[$maNum] = array('108', '/uploads/allimg/161130/1-1611301P010T6.png');
$maNum = 4;
$myaddons[$maNum] = array('109', '/uploads/allimg/161130/1-1611301P033D2.png');
$maNum = 5;
