<div class="tl_ir">
        <div class="imgRight">
            <a href="../tpls/aboutUs_team.html"><img src="{dede:global.cfg_templets_skin/}/img/about/Qualification.png" ></a>
        </div>
        <div class="textLeft">
            <img src="../../templets/ike/img/about/profile.png" class="profile">
            <h2>资质与荣誉</h2>
            <div class="text">
                <div class="textTop">
                    拥有ISO-9001“9000族质量管理体系认证证书”、ISO-14001“14000族环境管理体系认证证书”、ISO-27001“27000族信息安全管理体系认证证书”和6个软件著作权，并在北京新四板成功挂牌上市，代码为ZS2677。
                </div>
                <div class="textBottom">
                    艾佳以满足客户个性化需求为基础，快速响应，利用云计算与大数据的优势，以客户为中心，针对不同需求，整合通信、软件、系统集成、营销活动等资源，量身定制，以小而全的团队满足其个性化、精细化服务需求。
                </div>
            </div>
            <a href="../tpls/aboutUs_team.html">查看详情</a>
        </div>
    </div>