<div class="dynamic_con">
                    <div class="dycon_top">
                        <div class="toptext">
                            <div class="textitle">
							<a href="[field:arcurl/]" style="font-size:14px;font-weight:700;height:32px;width:305px;overflow:hidden;color:#555;">
								[field:title/]
							</a>
							</div>
                            <p class="text">
								<a href="[field:arcurl/]" style="color:#555;">
									[field:description/]
								</a>
                            </p>
                            <span>发布时间：[field:pubdate function=MyDate('Y-m-d',@me)/]</span>
                        </div>
                        <div class="topimg">
							<a href="[field:arcurl/]">
								[field:image/]
							</a>
                        </div>
                    </div>