<div class="tl_ir">
        <div class="imgRight">
            <a href="../tpls/aboutUs_team.html"><img src="{dede:global.cfg_templets_skin/}/img/about/picture1.png" ></a>
        </div>
        <div class="textLeft">
            <img src="../../templets/ike/img/about/profile.png" class="profile">
            <h2>我们的福利</h2>
            <div class="text">
                <div class="textTop">
                    北京艾佳天诚信息技术有限公司成立于2013年，注册资本3000万元，是一家专业的信息技术服务公司，拥有ISO-9001“9000族质量管理体系认证证书”、ISO-14001“14000族环境管理体系认证证书”、ISO-27001“27000族信息安全管理体系认证证书”和6个软件著作权，并在北京新四板成功挂牌上市，代码为ZS2677。
                </div>
                <div class="textBottom">
                    公司核心业务包括通信类、软件类、系统集成类、营销活动策划类等
                </div>
            </div>
            <a href="../tpls/aboutUs_team.html">查看详情</a>
        </div>
    </div>