<div class="il_tr">
        <div class="imgLeft">
            <a href="../tpls/aboutUs_team.html"> <img src="{dede:global.cfg_templets_skin/}/img/about/Guarantee.png" ></a>
        </div>
        <div class="textRight">
            <img src="../../templets/ike/img/about/profile.png" class="profile">
            <h2>[field:title/]</h2>
            [field:description/]
            <a href="[field:arcurl/]">查看详情</a>
        </div>
    </div>