<div class="tl_ir">
        <div class="imgRight">
            <a href="../tpls/aboutUs_team.html"> <img src="../img/about/Team-support.png" ></a>
        </div>
        <div class="textLeft">
            <img src="{dede:global.cfg_templets_skin/}/img/about/profile.png" class="profile">
            <h2>团队支撑</h2>
            <div class="text">
                <div class="textTop">
                    公司拥有2个通信与广电专业一级建造师，2个机电专业二级建造师，5个电子工程专业中级职称，15个八大员，2个概预算员，5个持有登高证的专业作业人员，7个持有电工证的特殊作业人员，拥有具备中兴技能认证的资格证书35张，具备华为认证的资格证书32张。
                </div>
                <div class="textBottom">
                    拥有专业项目管理经验的项目经理13人，从事网优工作5年以上，无线网规网优的资深工程师32名，其余各类专业技术人员25名。
                </div>
            </div>
            <a href="../tpls/aboutUs_team.html">查看详情</a>
        </div>
    </div>