<div class="il_tr">
        <div class="imgLeft">
            <a href="../tpls/aboutUs_team.html"> <img src="{dede:global.cfg_templets_skin/}/img/about/we.png" ></a>
        </div>
        <div class="textRight">
            <img src="{dede:global.cfg_templets_skin/}/img/about/profile.png" class="profile">
            <h2>我们</h2>
            <div class="text">
                <div class="textTop">北京艾佳天诚信息技术有限公司成立于2013年，注册资本3000万元，是一家专业的信息技术服务公司，拥有ISO-9001北京艾佳天诚信息技术有限公司成立于2013年，注册资本3000万元，是一家专业的信息技术服务公司，拥有ISO-9001北京艾佳天诚信息技术有限公司成立于2013年，注册资本3000万元，是一家专业的信息技术服务公司，拥有ISO-9001</div>
                <div class="textBottom">北京艾佳天诚信息技术有限公司成立于2013年，注册资本3000万元，是一家专业的信息技术服务公司，拥有ISO-9001</div>
            </div>
            <a href="../tpls/aboutUs_team.html">查看详情</a>
        </div>
    </div>