<li>
                [field:image/]
                <div class="list_a">
                    <a href="[field:arcurl/]" >
                        <h2>[field:title/]</h2>
                    </a>
                    <a href="[field:arcurl/]" >
                        <p>又是一年月满时，多年来，艾佳始终秉承“点滴做起，追求完善”的公司理念，为员工创造和谐、富有激情的工作环境。艾佳获得的每一分成绩都离不开员工们的共同努力1111111111111111111111111111111。

                        </p>
                    </a>
                </div>
                <div class="readcount">
                    <div class="_date">
                        [field:pubdate function=MyDate('Y-m',@me)/] <p>[field:pubdate function=MyDate('d',@me)/]</p>
                    </div>
                    <div class="looktime">查看：<span>[field:click/]</span>次</div>
                </div>
            </li>