<div class="il_tr">
			<div class="imgLeft">
				<a href="{dede:field name='typeurl'/}">{dede:field.content/}</a>
			</div>
			<div class="textRight">
				<img src="{dede:global.cfg_templets_skin/}/img/about/profile.png" class="profile">
				<h2>{dede:field name='typename'/}</h2>
				<div class="text">
					<div class="textTop">
						{dede:field name='description'/}
					</div>
					
				</div>
				<a href="{dede:field name='typeurl'/}">查看详情</a>
			</div>
		</div>