<?php
$z[0]=Array("global","",82,108);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",151,183);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",235,267);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",319,351);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",387,419);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",466,498);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",576,603);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("include","",654,691);
$z[7][4]['filename']="header.htm";
$z[8]=Array("field","",786,806);
$z[8][4]['name']="litpic";
$z[9]=Array("global","",894,926);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",969,988);
$z[10][4]['name']="title";
$z[11]=Array("field","",1119,1143);
$z[11][4]['name']="shorttitle";
$z[12]=Array("field","",1153,1171);
$z[12][4]['name']="body";
$z[13]=Array("channelartlist","\r\n					<a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a>\r\n				",1290,1443);
$z[13][4]['typeid']="21";
$z[14]=Array("channelartlist","\r\n\r\n					{dede:arclist titlelen='60' row='8'}\r\n\r\n\r\n                    <li >\r\n                        <a href=\"[field:arcurl/]\" ><p> [field:title/]</p> [field:pubdate function=MyDate('Y-m-d',@me)/]</a>\r\n                    </li>\r\n					{/dede:arclist}\r\n\r\n\r\n				",1570,1892);
$z[14][4]['row']="";
$z[14][4]['typeid']="21";
$z[15]=Array("include","",1980,2017);
$z[15][4]['filename']="footer.htm";

?>