<?php
$z[0]=Array("global","",82,108);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",151,183);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",235,267);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",318,350);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",386,418);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",465,497);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",550,582);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",660,687);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("include","",739,776);
$z[8][4]['filename']="header.htm";
$z[9]=Array("channelartlist","\r\n		\r\n		<div class=\"il_tr\">\r\n			<div class=\"imgLeft\">\r\n				<a href=\"{dede:field name='typeurl'/}\">{dede:field.content/}</a>\r\n			</div>\r\n			<div class=\"textRight\">\r\n				<img src=\"{dede:global.cfg_templets_skin/}/img/about/profile.png\" class=\"profile\">\r\n				<h2>{dede:field name='typename'/}</h2>\r\n				<div class=\"text\">\r\n					{dede:field name='description'/}					\r\n				</div>\r\n				<a href=\"{dede:field name='typeurl'/}\">查看详情</a>\r\n			</div>\r\n		</div>\r\n	",803,1317);
$z[9][4]['typeid']="21";
$z[10]=Array("include","",1600,1637);
$z[10][4]['filename']="footer.htm";

?>