<form name='infoguide' method='get' action='/plus/list.php'>


			<input type='hidden' name='tid' value='[field:typeid /]' />

			<input type='hidden' name='channelid' value='-8' />

			<span class='infosearchtxt'>关键字：</span><span><input type='text' name='keyword' value=''placeholder="职位" class="ipt-txt input_join" /></span>

			<button><input type='submit' value='' class="btn-2" style='cursor:pointer' /></button>
			</form>