<div class="img_l" style="background:url('[field:litpic/];') no-repeat">
                <div class="type"> <span>[field:typelink/]</span></div></a>
                <p>
                   [field:title/]
                </p>
                <div class="more">
                    <a href="[field:arcurl/]">查看更多</a>
                </div>
            </div>
			<div style="float:left;width:10px;height:400px;"></div>