<div class="il_tr">
			<div class="imgLeft">
				<a href="../tpls/aboutUs_team.html">[field:content/]</a>
			</div>
			<div class="textRight">
				<img src="{dede:global.cfg_templets_skin/}/img/about/profile.png" class="profile">
				<h2>[field:title/]</h2>
				<div class="text">
					<div class="textTop">
						[field:description/]
					</div>
					
				</div>
				<a href="../tpls/aboutUs_team.html">查看详情</a>
			</div>
		</div>