<div class="tl_ir">
        <div class="imgRight">
            <a href="../tpls/aboutUs_team.html"><img src="{dede:global.cfg_templets_skin/}/img/about/picture1.png" ></a>
        </div>
        <div class="textLeft">
            <img src="../../templets/ike/img/about/profile.png" class="profile">
            <h2>[field:title/]</h2>
            [field:description/]
            <a href="[field:arcurl/]">查看详情</a>
        </div>
    </div>