<div class="il_tr">
        <div class="imgLeft">
            <a href="../tpls/aboutUs_team.html"> <img src="{dede:global.cfg_templets_skin/}/img/about/Guarantee.png" ></a>
        </div>
        <div class="textRight">
            <img src="{dede:global.cfg_templets_skin/}/img/about/profile.png" class="profile">
            <h2>保障体系</h2>
            <div class="text">
                <div class="textTop">
                    公司在大数据与云平台的基础上，集成ERP、CRM、SCM的核心要素，建立了ISSP-智能服务共享平台，应用数学建模和统计分析技巧，识别工作中各关键数据变量之间的关系，通过规划-设计-实施-反馈-再规划的智能学习系统，规范流程，实现了北京、湖南、广州、佛山、珠海、江门、湛江等多地联动作业，确保工作的及时性和有效性。
                </div>
                <div class="textBottom">
                    艾佳以满足客户个性化需求为基础，快速响应，利用云计算与大数据的优势，以客户为中心，针对不同需求，整合通信、软件、系统集成、营销活动等资源，量身定制，以小而全的团队满足其个性化、精细化服务需求。
                </div>
            </div>
            <a href="../tpls/aboutUs_team.html">查看详情</a>
        </div>
    </div>