<?php
$z[0]=Array("global","",162,194);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",250,282);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",346,378);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",480,504);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",514,546);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",591,617);
$z[5][4]['name']="cfg_powerby";

?>