<?php
$z[0]=Array("global","",94,126);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",413,445);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",545,577);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",814,839);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",851,883);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1009,1034);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("type","\r\n\r\n			<a href='[field:typelink/]'>[field:typename/]</a>\r\n\r\n			",1089,1185);
$z[6][4]['typeid']="21";
$z[7]=Array("channelartlist","\r\n                <a href=\"{dede:field name='typeurl'/}\" class=\"serviceBtn\">{dede:field name='typename'/} <i></i></a>\r\n                <ul class=\"subnav\">\r\n				{dede:channel type='son' noself='yes'}\r\n                    <li>\r\n                        <a href=\"[field:typelink/]#stft\" goId=\"\">[field:typename/]</a>\r\n                    </li>\r\n				{/dede:channel}\r\n\r\n                </ul>\r\n			",1244,1692);
$z[7][4]['typeid']="22,22";
$z[8]=Array("autochannel","\r\n                <a href='[field:typelink/]'>[field:typename/]</a>\r\n			",1725,1857);
$z[8][4]['partsort']="3";
$z[8][4]['typeid']="17";
$z[9]=Array("type","\r\n\r\n				<a href='[field:typelink/]'>[field:typename/]</a>\r\n\r\n				",1912,2010);
$z[9][4]['typeid']="33";
$z[10]=Array("type","\r\n                <a href=\"[field:typelink/]\">联系我们</a>\r\n			",2052,2152);
$z[10][4]['typeid']="34";
$z[11]=Array("geturl","\r\n			@me = GetCurUrl();\r\n			if(@me == '/dedecms/' || @me=='/dedecms/index.php'){\r\n				@me='首页';\r\n			}else{\r\n				@me='';\r\n			}\r\n		",2198,2371);
$z[11][4]['runphp']="yes";
$z[12]=Array("type","[field:typename/]",2388,2428);

?>