<?php
$z[0]=Array("global","",95,127);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",414,446);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",546,578);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",815,842);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",854,886);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1013,1040);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("type","\r\n\r\n			<a href='[field:typelink/]'>[field:typename/]</a>\r\n\r\n			",1095,1191);
$z[6][4]['typeid']="21";
$z[7]=Array("channelartlist","\r\n                <a href=\"{dede:field name='typeurl'/}\" class=\"serviceBtn\">{dede:field name='typename'/} <i></i></a>\r\n                <ul class=\"subnav\">\r\n				{dede:channel type='son' noself='yes'}\r\n                    <li>\r\n                        <a href=\"[field:typelink/]#stft\" goId=\"\">[field:typename/]</a>\r\n                    </li>\r\n				{/dede:channel}\r\n\r\n                </ul>\r\n			",1250,1698);
$z[7][4]['typeid']="22,22";
$z[8]=Array("autochannel","\r\n                <a href='[field:typelink/]'>[field:typename/]</a>\r\n			",1731,1863);
$z[8][4]['partsort']="1";
$z[8][4]['typeid']="17";
$z[9]=Array("type","\r\n\r\n				<a href='[field:typelink/]'>[field:typename/]</a>\r\n\r\n				",1918,2016);
$z[9][4]['typeid']="33";
$z[10]=Array("type","\r\n                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n			",2058,2163);
$z[10][4]['typeid']="34";
$z[11]=Array("geturl","  \r\n				\$cu = GetCurUrl();  \r\n				if( \$cu == '/' || \$cu == '/index.php' ){  \r\n					@me = '首页';  \r\n				}else{\r\n					@me='';\r\n				}\r\n			",2213,2391);
$z[11][4]['runphp']="yes";
$z[12]=Array("type","[field:typename/]",2410,2450);

?>