<?php
$z[0]=Array("global","",137,169);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",221,253);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",303,335);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",371,403);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",450,482);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1284,1321);
$z[5][4]['filename']="header.htm";
$z[6]=Array("infolink","\r\n                <option value=\"gz\">[field:linkalltype/]</option>\r\n			",1472,1574);
$z[7]=Array("infoguide","\r\n\r\n			<form name='infoguide' method='get' action='/dedecms/plus/list.php'>\r\n\r\n\r\n			<input type='hidden' name='tid' value='[field:typeid /]' />\r\n\r\n			<input type='hidden' name='channelid' value='-8' />\r\n\r\n			<span class='infosearchtxt'>关键字：</span><span><input type='text' name='keyword' value='' class=\"ipt-txt input_join\" /></span>\r\n\r\n			<button><input type='submit' value='' class=\"btn-2\" style='cursor:pointer' /></button>\r\n			</form>\r\n\r\n			",1646,2131);
$z[8]=Array("list","\r\n            <tr>\r\n                <td>\r\n                    <a href=\"[field:arcurl/]\" title=\"jav\">\r\n                        [field:title/]\r\n                    </a>\r\n                </td>\r\n                <td>广州</td>\r\n                <td>面议</td>\r\n            </tr>\r\n		",2360,2675);
$z[8][4]['pagesize']="20";
$z[9]=Array("pagelist","",2776,2847);
$z[9][4]['listsize']="5";
$z[9][4]['listitem']="info,index,end,pre,next,pageno";
$z[10]=Array("global","",3040,3072);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",3128,3160);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",3224,3256);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",3389,3421);
$z[13][4]['name']="cfg_templets_skin";

?>