<?php
$z[0]=Array("global","",82,108);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",151,183);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",235,267);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",317,349);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",385,417);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",464,496);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",574,601);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("include","",1412,1449);
$z[7][4]['filename']="header.htm";
$z[8]=Array("infolink","\r\n                <option value=\"gz\">[field:linkalltype/]</option>\r\n			",1600,1702);
$z[9]=Array("infoguide","\r\n\r\n			<form name='infoguide' method='get' action='/plus/list.php'>\r\n\r\n\r\n			<input type='hidden' name='tid' value='[field:typeid /]' />\r\n\r\n			<input type='hidden' name='channelid' value='-8' />\r\n\r\n			<span class='infosearchtxt'>关键字：</span><span><input type='text' name='keyword' value=''placeholder=\"职位\" class=\"ipt-txt input_join\" /></span>\r\n\r\n			<button><input type='submit' value='' class=\"btn-2\" style='cursor:pointer' /></button>\r\n			</form>\r\n\r\n			",1774,2271);
$z[10]=Array("list","\r\n            <tr>\r\n                <td>\r\n                    <a href=\"[field:arcurl/]\" title=\"jav\">\r\n                        [field:title/]\r\n                    </a>\r\n                </td>\r\n                <td>[field:nativeplace/]</td>\r\n                <td>面议</td>\r\n            </tr>\r\n		",2500,2829);
$z[10][4]['pagesize']="20";
$z[11]=Array("pagelist","",2930,3001);
$z[11][4]['listsize']="5";
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[12]=Array("include","",3032,3069);
$z[12][4]['filename']="footer.htm";

?>