<?php
$z[0]=Array("global","",82,108);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",151,183);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",235,267);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",320,352);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",388,420);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",467,499);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",577,604);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("include","",655,692);
$z[7][4]['filename']="header.htm";
$z[8]=Array("sql","\r\n		[field:content/]\r\n	",749,843);
$z[8][4]['sql']="Select content from ike_arctype where id=33";
$z[9]=Array("field","",1028,1047);
$z[9][4]['name']="title";
$z[10]=Array("field","",1094,1112);
$z[10][4]['name']="body";
$z[11]=Array("arclistsg","\r\n                    <li >\r\n                        <a href=\"[field:arcurl/]\" ><p> [field:title/]</p> [field:pubdate function=MyDate('Y-m-d',@me)/]</a>\r\n                    </li>\r\n		",1291,1585);
$z[11][4]['row']="10";
$z[11][4]['titlelen']="24";
$z[11][4]['orderby']="pubdate";
$z[11][4]['channelid']="-8";
$z[11][4]['typeid']="33";
$z[11][4]['idlist']="";
$z[12]=Array("include","",1670,1707);
$z[12][4]['filename']="footer.htm";

?>